baseurl      = "https://gownkydo.tech/"
title        = "Hello friend - Gownkydo"
languageCode = "en-us"
defaultContentLanguage = "en"
theme        = "hello-friend-ng"
paginate     = 5

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[permalinks]
  posts = "/posts/:year/:month/:slug/"

[languages]
  [languages.en]
    title = "Hello Friend"
    subtitle = "Gownkydo"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    
    [languages.en.params.logo]
      logoMark     = ">"
      logoText = "./readPost"
      logoHomeLink = "/"

[params]
  homeSubtitle = "Guides, writeups, tips about programming and cybersecurity."
  enableRobotsTXT = true
  enableThemeToggle = false
  defaultTheme = "dark"
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"

  [[menu.main]]
    identifier = "archives"
    name       = "Archives"
    url        = "/archives/"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"

[[params.social]]
  name = "github"
  url = "https://github.com/gownkydo"

[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/gerardohgomez"

[[params.social]]
  name = "telegram"
  url = "https://t.me/gownkydo"

[params.footer]
    trademark = "2024-2025"
    rss = false
    copyright = true
    author = true
    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "<a href=\"https://github.com/gownkydo\">Gownkydo</a>"
    ]
