baseurl      = "https://gownkydo.github.io"
title        = "Hello friend - Gownkydo"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 5

[params]
  dateform        = "Jan 2, 2006"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  disableReadOtherPosts = false
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hello Friend"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

[params.author]
  image = "images/profile.jpg"
  name = "Gownkydo"
  greeting = "Guides, writeups, tips about programing and cybersecurity."
  icon = ":bullseye:"

[[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/posts"

[[menu.main]]
  identifier = "tag"
  name       = "Tag"
  url        = "/tags"

[[menu.main]]
  identifier = "about"
  name       = "About"
  url        = "/about"

[[params.social]]
  name = "github"
  url = "https://github.com/gownkydo"

[[params.social]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/gerardohgomez"

[[params.social]]
  name = "telegram"
  url = "https://t.me/gownkydo"
