baseurl      = "https://gownkydo.github.io"
title        = "Hello friend - Gownkydo"
languageCode = "en-en"
theme        = "hello-friend-ng"
paginate     = 5

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  disableReadOtherPosts = false
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hello Friend"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

  [languages.en.params]
    subtitle  = "Gownkydo"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

[[params.social]]
  name = "github"
  url = "https://github.com/gownkydo"

[[params.social]]
  name = "LinkdIn"
  url = "https://linkedin.com/in/4strodev"

[[params.social]]
  name = "telegram"
  url = "https://t.me/gownkydo"
